services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/metai.db
      - INFLUX_URL=http://192.168.0.79:8181/api/v3/write_lp?db=metai
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - api
    restart: unless-stopped
